# Generated by Django 2.2.6 on 2019-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendTimelinePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_user_name', models.CharField(max_length=30)),
                ('friend_user_name', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
            ],
        ),
    ]
