# Generated by Django 2.2.6 on 2019-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friendtimelinepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('msg_content', models.TextField()),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('postContent', models.TextField()),
                ('postTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'UserPosts',
            },
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='created_by',
            new_name='person_user_name',
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together={('person_user_name', 'group_name')},
        ),
    ]
