# Generated by Django 2.2.6 on 2019-10-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191020_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('group_name', models.CharField(max_length=250)),
                ('admin_id', models.CharField(max_length=250)),
                ('privacy', models.CharField(max_length=250)),
                ('group_type', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('request', models.IntegerField(default=0)),
                ('user_id', models.CharField(max_length=250)),
                ('admin_id', models.CharField(default=0, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=' default ', max_length=250)),
                ('First_name', models.CharField(default=' ', max_length=250)),
                ('Last_name', models.CharField(default=' ', max_length=250)),
                ('Bio', models.CharField(default=' ', max_length=850)),
                ('Privacy_setting', models.CharField(default='public', max_length=250)),
                ('Phone_number', models.IntegerField(default=0)),
                ('user_type', models.CharField(default='Casual', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250)),
                ('group_id', models.IntegerField(default=0)),
            ],
        ),
    ]
