# Generated by Django 2.2.6 on 2019-10-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_groupnew_grouprequest_updateprofile_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
                ('postTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, unique=True)),
                ('page_des', models.CharField(max_length=100)),
                ('page_admin', models.CharField(max_length=30)),
            ],
        ),
    ]
