# Generated by Django 2.2.5 on 2019-10-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30)),
                ('page_admin', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
                ('postTime', models.DateTimeField()),
            ],
        ),
    ]
