# Generated by Django 2.2.5 on 2019-10-20 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pageposts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.RemoveField(
            model_name='pageposts',
            name='page_admin',
        ),
    ]
