# Generated by Django 2.2.6 on 2019-10-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pageposts_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyRequests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=30)),
                ('person_name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
