# Generated by Django 2.2.5 on 2019-10-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_moneyrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
