# Generated by Django 2.2.5 on 2019-10-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191020_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, unique=True)),
                ('page_des', models.CharField(max_length=100)),
                ('page_admin', models.CharField(max_length=30)),
            ],
        ),
    ]
