# Generated by Django 2.2.5 on 2019-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_userposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedBy', models.CharField(max_length=20)),
                ('postContent', models.TextField()),
                ('postTime', models.DateTimeField()),
                ('postedOn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserPosts',
            },
        ),
    ]
