# Generated by Django 2.2.6 on 2019-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('userid', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
